# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/andryushka/Programms/Unreal_Engine

TARGETS = \
	ShootThemUp-Android-DebugGame  \
	ShootThemUp-Android-Development  \
	ShootThemUp-Android-Shipping  \
	ShootThemUp-Linux-DebugGame  \
	ShootThemUp-Linux-Development  \
	ShootThemUp-Linux-Shipping  \
	ShootThemUp-LinuxArm64-DebugGame  \
	ShootThemUp-LinuxArm64-Development  \
	ShootThemUp-LinuxArm64-Shipping  \
	ShootThemUp \
	ShootThemUpEditor-Linux-DebugGame  \
	ShootThemUpEditor-Linux-Development  \
	ShootThemUpEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend ShootThemUpEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug ShootThemUpEditor-Linux-Debug


ShootThemUp-Android-DebugGame:
	 $(BUILD) ShootThemUp Android DebugGame  -Project="/home/andryushka/Documents/Projects/ShootThemUpThree/ShootThemUp/ShootThemUp.uproject" $(ARGS)

ShootThemUp-Android-Development:
	 $(BUILD) ShootThemUp Android Development  -Project="/home/andryushka/Documents/Projects/ShootThemUpThree/ShootThemUp/ShootThemUp.uproject" $(ARGS)

ShootThemUp-Android-Shipping:
	 $(BUILD) ShootThemUp Android Shipping  -Project="/home/andryushka/Documents/Projects/ShootThemUpThree/ShootThemUp/ShootThemUp.uproject" $(ARGS)

ShootThemUp-Linux-DebugGame:
	 $(BUILD) ShootThemUp Linux DebugGame  -Project="/home/andryushka/Documents/Projects/ShootThemUpThree/ShootThemUp/ShootThemUp.uproject" $(ARGS)

ShootThemUp-Linux-Development:
	 $(BUILD) ShootThemUp Linux Development  -Project="/home/andryushka/Documents/Projects/ShootThemUpThree/ShootThemUp/ShootThemUp.uproject" $(ARGS)

ShootThemUp-Linux-Shipping:
	 $(BUILD) ShootThemUp Linux Shipping  -Project="/home/andryushka/Documents/Projects/ShootThemUpThree/ShootThemUp/ShootThemUp.uproject" $(ARGS)

ShootThemUp-LinuxArm64-DebugGame:
	 $(BUILD) ShootThemUp LinuxArm64 DebugGame  -Project="/home/andryushka/Documents/Projects/ShootThemUpThree/ShootThemUp/ShootThemUp.uproject" $(ARGS)

ShootThemUp-LinuxArm64-Development:
	 $(BUILD) ShootThemUp LinuxArm64 Development  -Project="/home/andryushka/Documents/Projects/ShootThemUpThree/ShootThemUp/ShootThemUp.uproject" $(ARGS)

ShootThemUp-LinuxArm64-Shipping:
	 $(BUILD) ShootThemUp LinuxArm64 Shipping  -Project="/home/andryushka/Documents/Projects/ShootThemUpThree/ShootThemUp/ShootThemUp.uproject" $(ARGS)

ShootThemUp: ShootThemUp-Linux-Development

ShootThemUpEditor-Linux-DebugGame:
	 $(BUILD) ShootThemUpEditor Linux DebugGame  -Project="/home/andryushka/Documents/Projects/ShootThemUpThree/ShootThemUp/ShootThemUp.uproject" $(ARGS)

ShootThemUpEditor-Linux-Development:
	 $(BUILD) ShootThemUpEditor Linux Development  -Project="/home/andryushka/Documents/Projects/ShootThemUpThree/ShootThemUp/ShootThemUp.uproject" $(ARGS)

ShootThemUpEditor: ShootThemUpEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/andryushka/Documents/Projects/ShootThemUpThree/ShootThemUp/ShootThemUp.uproject" -Game 

.PHONY: $(TARGETS)
